version: '3.8'

services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always