version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3010:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - USE_OLLAMA_DOCKER=true
    depends_on:
      - ollama
    restart: unless-stopped
    
volumes:
  ollama: